Traceback (most recent call last):
  File "/home/runner/.cache/pypoetry/virtualenvs/mtbp3-STzYEG9e-py3.10/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/runner/.cache/pypoetry/virtualenvs/mtbp3-STzYEG9e-py3.10/lib/python3.10/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/runner/.cache/pypoetry/virtualenvs/mtbp3-STzYEG9e-py3.10/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/runner/.cache/pypoetry/virtualenvs/mtbp3-STzYEG9e-py3.10/lib/python3.10/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/home/runner/.cache/pypoetry/virtualenvs/mtbp3-STzYEG9e-py3.10/lib/python3.10/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/runner/.cache/pypoetry/virtualenvs/mtbp3-STzYEG9e-py3.10/lib/python3.10/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
print("\n".join(ctoc.find_section_given_words(["REMS","isE"], outfmt='tree')))
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mValueError[0m                                Traceback (most recent call last)
Cell [0;32mIn[8], line 1[0m
[0;32m----> 1[0m [38;5;28mprint[39m([38;5;124m"[39m[38;5;130;01m\n[39;00m[38;5;124m"[39m[38;5;241m.[39mjoin([43mctoc[49m[38;5;241;43m.[39;49m[43mfind_section_given_words[49m[43m([49m[43m[[49m[38;5;124;43m"[39;49m[38;5;124;43mREMS[39;49m[38;5;124;43m"[39;49m[43m,[49m[38;5;124;43m"[39;49m[38;5;124;43misE[39;49m[38;5;124;43m"[39;49m[43m][49m[43m,[49m[43m [49m[43moutfmt[49m[38;5;241;43m=[39;49m[38;5;124;43m'[39;49m[38;5;124;43mtree[39;49m[38;5;124;43m'[39;49m[43m)[49m))

File [0;32m~/work/mtbp3/mtbp3/mtbp3/health/ectd.py:52[0m, in [0;36mctoc_by_fda.find_section_given_words[0;34m(self, words, outfmt, include, to_right)[0m
[1;32m     50[0m [38;5;28;01mdef[39;00m [38;5;21mfind_section_given_words[39m([38;5;28mself[39m, words, outfmt[38;5;241m=[39m[38;5;124m'[39m[38;5;124msimple[39m[38;5;124m'[39m, include[38;5;241m=[39m[38;5;124m'[39m[38;5;124mup[39m[38;5;124m'[39m, to_right[38;5;241m=[39m[38;5;28;01mFalse[39;00m):
[1;32m     51[0m     [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m [38;5;28misinstance[39m(words, [38;5;28mstr[39m) [38;5;129;01mor[39;00m [38;5;129;01mnot[39;00m words:
[0;32m---> 52[0m         [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m([38;5;124m"[39m[38;5;124mstr must be a nonempty string[39m[38;5;124m"[39m)
[1;32m     53[0m     [38;5;28;01mif[39;00m include [38;5;129;01mnot[39;00m [38;5;129;01min[39;00m [[38;5;124m'[39m[38;5;124mup[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mboth[39m[38;5;124m'[39m]:
[1;32m     54[0m         [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m([38;5;124m"[39m[38;5;124mInvalid value for include. Supported values are [39m[38;5;124m'[39m[38;5;124mup[39m[38;5;124m'[39m[38;5;124m and [39m[38;5;124m'[39m[38;5;124mboth[39m[38;5;124m'[39m[38;5;124m.[39m[38;5;124m"[39m)

[0;31mValueError[0m: str must be a nonempty string

