Traceback (most recent call last):
  File "/home/runner/.cache/pypoetry/virtualenvs/mtbp3-STzYEG9e-py3.10/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/runner/.cache/pypoetry/virtualenvs/mtbp3-STzYEG9e-py3.10/lib/python3.10/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/runner/.cache/pypoetry/virtualenvs/mtbp3-STzYEG9e-py3.10/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/runner/.cache/pypoetry/virtualenvs/mtbp3-STzYEG9e-py3.10/lib/python3.10/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/home/runner/.cache/pypoetry/virtualenvs/mtbp3-STzYEG9e-py3.10/lib/python3.10/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/runner/.cache/pypoetry/virtualenvs/mtbp3-STzYEG9e-py3.10/lib/python3.10/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
print(emt.find_smq(smq_names[0]).T)
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mValueError[0m                                Traceback (most recent call last)
Cell [0;32mIn[3], line 1[0m
[0;32m----> 1[0m [38;5;28mprint[39m([43memt[49m[38;5;241;43m.[39;49m[43mfind_smq[49m[43m([49m[43msmq_names[49m[43m[[49m[38;5;241;43m0[39;49m[43m][49m[43m)[49m[38;5;241m.[39mT)

File [0;32m~/work/mtbp3/mtbp3/mtbp3/util/emt.py:418[0m, in [0;36mEmt.find_smq[0;34m(self, terms, ignore_case)[0m
[1;32m    416[0m         out [38;5;241m=[39m df[df[[38;5;241m1[39m] [38;5;241m==[39m terms[[38;5;241m0[39m]]
[1;32m    417[0m     out [38;5;241m=[39m out[38;5;241m.[39miloc[:, :[38;5;241m-[39m[38;5;241m1[39m]
[0;32m--> 418[0m     [43mout[49m[38;5;241;43m.[39;49m[43mcolumns[49m [38;5;241m=[39m [[38;5;124m'[39m[38;5;124mid[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mname[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mlevel[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mdescription[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124msource[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mnote[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mMedDRA_version[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mstatus[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124malgorithm[39m[38;5;124m'[39m]
[1;32m    419[0m     [38;5;28;01mreturn[39;00m out
[1;32m    420[0m [38;5;28;01melif[39;00m [38;5;28mlen[39m(terms)[38;5;241m>[39m[38;5;241m1[39m:

File [0;32m~/.cache/pypoetry/virtualenvs/mtbp3-STzYEG9e-py3.10/lib/python3.10/site-packages/pandas/core/generic.py:6310[0m, in [0;36mNDFrame.__setattr__[0;34m(self, name, value)[0m
[1;32m   6308[0m [38;5;28;01mtry[39;00m:
[1;32m   6309[0m     [38;5;28mobject[39m[38;5;241m.[39m[38;5;21m__getattribute__[39m([38;5;28mself[39m, name)
[0;32m-> 6310[0m     [38;5;28;01mreturn[39;00m [38;5;28;43mobject[39;49m[38;5;241;43m.[39;49m[38;5;21;43m__setattr__[39;49m[43m([49m[38;5;28;43mself[39;49m[43m,[49m[43m [49m[43mname[49m[43m,[49m[43m [49m[43mvalue[49m[43m)[49m
[1;32m   6311[0m [38;5;28;01mexcept[39;00m [38;5;167;01mAttributeError[39;00m:
[1;32m   6312[0m     [38;5;28;01mpass[39;00m

File [0;32mproperties.pyx:69[0m, in [0;36mpandas._libs.properties.AxisProperty.__set__[0;34m()[0m

File [0;32m~/.cache/pypoetry/virtualenvs/mtbp3-STzYEG9e-py3.10/lib/python3.10/site-packages/pandas/core/generic.py:813[0m, in [0;36mNDFrame._set_axis[0;34m(self, axis, labels)[0m
[1;32m    808[0m [38;5;250m[39m[38;5;124;03m"""[39;00m
[1;32m    809[0m [38;5;124;03mThis is called from the cython code when we set the `index` attribute[39;00m
[1;32m    810[0m [38;5;124;03mdirectly, e.g. `series.index = [1, 2, 3]`.[39;00m
[1;32m    811[0m [38;5;124;03m"""[39;00m
[1;32m    812[0m labels [38;5;241m=[39m ensure_index(labels)
[0;32m--> 813[0m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_mgr[49m[38;5;241;43m.[39;49m[43mset_axis[49m[43m([49m[43maxis[49m[43m,[49m[43m [49m[43mlabels[49m[43m)[49m
[1;32m    814[0m [38;5;28mself[39m[38;5;241m.[39m_clear_item_cache()

File [0;32m~/.cache/pypoetry/virtualenvs/mtbp3-STzYEG9e-py3.10/lib/python3.10/site-packages/pandas/core/internals/managers.py:238[0m, in [0;36mBaseBlockManager.set_axis[0;34m(self, axis, new_labels)[0m
[1;32m    236[0m [38;5;28;01mdef[39;00m [38;5;21mset_axis[39m([38;5;28mself[39m, axis: AxisInt, new_labels: Index) [38;5;241m-[39m[38;5;241m>[39m [38;5;28;01mNone[39;00m:
[1;32m    237[0m     [38;5;66;03m# Caller is responsible for ensuring we have an Index object.[39;00m
[0;32m--> 238[0m     [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_validate_set_axis[49m[43m([49m[43maxis[49m[43m,[49m[43m [49m[43mnew_labels[49m[43m)[49m
[1;32m    239[0m     [38;5;28mself[39m[38;5;241m.[39maxes[axis] [38;5;241m=[39m new_labels

File [0;32m~/.cache/pypoetry/virtualenvs/mtbp3-STzYEG9e-py3.10/lib/python3.10/site-packages/pandas/core/internals/base.py:98[0m, in [0;36mDataManager._validate_set_axis[0;34m(self, axis, new_labels)[0m
[1;32m     95[0m     [38;5;28;01mpass[39;00m
[1;32m     97[0m [38;5;28;01melif[39;00m new_len [38;5;241m!=[39m old_len:
[0;32m---> 98[0m     [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m(
[1;32m     99[0m         [38;5;124mf[39m[38;5;124m"[39m[38;5;124mLength mismatch: Expected axis has [39m[38;5;132;01m{[39;00mold_len[38;5;132;01m}[39;00m[38;5;124m elements, new [39m[38;5;124m"[39m
[1;32m    100[0m         [38;5;124mf[39m[38;5;124m"[39m[38;5;124mvalues have [39m[38;5;132;01m{[39;00mnew_len[38;5;132;01m}[39;00m[38;5;124m elements[39m[38;5;124m"[39m
[1;32m    101[0m     )

[0;31mValueError[0m: Length mismatch: Expected axis has 7 elements, new values have 9 elements

