Traceback (most recent call last):
  File "/home/runner/.cache/pypoetry/virtualenvs/mtbp3-STzYEG9e-py3.10/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/runner/.cache/pypoetry/virtualenvs/mtbp3-STzYEG9e-py3.10/lib/python3.10/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/runner/.cache/pypoetry/virtualenvs/mtbp3-STzYEG9e-py3.10/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/runner/.cache/pypoetry/virtualenvs/mtbp3-STzYEG9e-py3.10/lib/python3.10/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/home/runner/.cache/pypoetry/virtualenvs/mtbp3-STzYEG9e-py3.10/lib/python3.10/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/runner/.cache/pypoetry/virtualenvs/mtbp3-STzYEG9e-py3.10/lib/python3.10/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from mtbp3.seq import ictvvmrview
vmr = ictvvmrview.ictvvmr(vmr_file_path = "")

------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mFileNotFoundError[0m                         Traceback (most recent call last)
Cell [0;32mIn[12], line 2[0m
[1;32m      1[0m [38;5;28;01mfrom[39;00m [38;5;21;01mmtbp3[39;00m[38;5;21;01m.[39;00m[38;5;21;01mseq[39;00m [38;5;28;01mimport[39;00m ictvvmrview
[0;32m----> 2[0m vmr [38;5;241m=[39m [43mictvvmrview[49m[38;5;241;43m.[39;49m[43mictvvmr[49m[43m([49m[43mvmr_file_path[49m[43m [49m[38;5;241;43m=[39;49m[43m [49m[38;5;124;43m"[39;49m[38;5;124;43m"[39;49m[43m)[49m

File [0;32m~/work/mtbp3/mtbp3/mtbp3/seq/ictvvmrview.py:63[0m, in [0;36mictvvmr.__init__[0;34m(self, vmr_file_path)[0m
[1;32m     60[0m     [38;5;28mself[39m[38;5;241m.[39mvmr_version [38;5;241m=[39m [38;5;124m"[39m[38;5;124mexample[39m[38;5;124m"[39m
[1;32m     62[0m [38;5;28mself[39m[38;5;241m.[39mvmr_column_names [38;5;241m=[39m []
[0;32m---> 63[0m [38;5;28mself[39m[38;5;241m.[39mvmr [38;5;241m=[39m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m__load_list[49m[43m([49m[43m)[49m
[1;32m     65[0m [38;5;28;01mif[39;00m [38;5;28mself[39m[38;5;241m.[39mvmr [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m:
[1;32m     66[0m     [38;5;28mself[39m[38;5;241m.[39mvmr_column_names [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39mvmr[38;5;241m.[39mcolumns[38;5;241m.[39mtolist()

File [0;32m~/work/mtbp3/mtbp3/mtbp3/seq/ictvvmrview.py:140[0m, in [0;36mictvvmr.__load_list[0;34m(self)[0m
[1;32m    138[0m     [38;5;28;01mreturn[39;00m df
[1;32m    139[0m [38;5;28;01melse[39;00m:
[0;32m--> 140[0m     [38;5;28;01mraise[39;00m [38;5;167;01mFileNotFoundError[39;00m([38;5;124mf[39m[38;5;124m"[39m[38;5;124mFile not found: [39m[38;5;132;01m{[39;00mfile_path[38;5;132;01m}[39;00m[38;5;124m"[39m)

[0;31mFileNotFoundError[0m: File not found: /home/runner/work/mtbp3/mtbp3/mtbp3/util/../data/supp_seq/ICTV_VMR_MSL39v4_example.csv

